### ISSUE TITLE
request: a python_requires line in setup.py

### ISSUE THREAD

**Issue by brainwane** [benjamin-pillot/gis-tools#1]
Hi! Would you mind [adding a `python_requires` line in `setup.py`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) so that https://pypi.org/project/gis-tools/#description can say (in the sidebar) which versions of Python the package supports?

Thanks!

**Comment by benjaminpillot** [comment]
Done. Btw, the right git for gis-tools is now at benjaminpillot/gis-tools. Unfortunately, I've had some troubles when changing my username and mail, so this repository is not active anymore.

**Comment by brainwane** [comment]
Ah, thanks! My sympathies.
